version: '3.9'

services:

  db:
    image: postgres:16
    container_name: postgres
    restart: always

    environment:
      POSTGRES_DB: order-payment
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 12345

    ports:
      - "5434:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend

    container_name: springboot-app

    ports:
      - "8080:8080"

    depends_on:
      - db

  frontend:
    build:
      context: ./frontend

    container_name: angular-app

    ports:
      - "4200:80"

    depends_on:
      - backend

volumes:
  postgres_data: